### ISSUE TITLE
diff_classifier_demo.ipynb outputs empty CSV file

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#24]
The `diff_classifier_demo.ipynb` doesn't finish for me.

I run this code in `diff_classifier_demo.ipynb`:

``` python
tparams = {'frames': nframes, 'radius': 3.5, 
           'threshold': 0.0, 'do_median_filtering': False,
           'quality': 3.0, 'xdims': (0, 128), 'ydims': (1, 128),
           'median_intensity': 300.0, 'snr': 0.0, 'linking_max_distance': 15.0,
           'gap_closing_max_distance': 15.0, 'max_frame_gap': 7,
           'track_duration': 5.0}
ij.track(filename1, outfile, template=None, fiji_bin=None, tparams=tparams)
print("Done with tracking.  Should output file of name {}".format(outfile))
# /Users/scott/.bin/Fiji-20141125.app/Contents/MacOS/ImageJ-macosx --ij2 --headless --run /var/folders/_p/t_mfcz_90vx3shw664l6kpbr0000gq/T/tmpxwqtmmzh.py
# Done with tracking.  Should output file of name Traj_FakeTracks.csv
```

I've verified `/Users/scott/.bin/Fiji-20141125.app/Contents/MacOS/ImageJ-macosx` and `/var/folders/_p/t_mfcz_90vx3shw664l6kpbr0000gq/T/tmpxwqtmmzh.py` exist.

However, the `Traj_FakeTracks.csv` is empty:

``` shell
$ wc Traj_FakeTracks.csv
       0       0       0 Traj_FakeTracks.csv
```

This means that no data is in the "Calculate features and MSDs" section, and the rest of the demo can't be run.

**Comment by stsievert** [comment]
I'm not sure how changing any arguments in `tparams` will effect the tracking.

**Comment by ccurtis7** [comment]
This appears to be a larger problem than I anticipated. This seriously was working three weeks ago before I went on break, and some update somewhere on the Python side or the ImageJ side seems to have broken it.

The problem comes down to the `imagej.track` function, which runs ImageJ as a subprocess. I tried rerunning the demo notebook as you did, and also got a completely empty csv file. This was confusing to me, because usually, even if the tracking parameters are slightly off, you will get SOME information from the ImageJ log as it sets up the tracking parameters, even if no trajectories were detected. I have never gotten a completely empty csv file.

This was a clue that the tracking may not even be occurring at all: Trackmate hasn't even been initiated. I tried copying the commands normally stored in a temp file as `test.py` and used the command `sudo /home/ubuntu/.bin/Fiji-20141125.app/ImageJ-linux64 --ij2 --headless --run test
s.py` in the shell to see what output I get. I end up getting a long list of errors, which I will show here:

`OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.IllegalArgumentException: Cannot handle replace call to list in ij.Menus's public static synchronized java.lang.String[] getPlugins()
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:724)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:649)
        at net.imagej.patcher.LegacyExtensions.addExtraPlugins(LegacyExtensions.java:475)
        at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:175)
        at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:308)
        at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:109)
        at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:101)
        at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:495)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:397)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
        at net.imagej.legacy.DefaultLegacyService.<clinit>(DefaultLegacyService.java:124)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:302)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:269)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:231)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:166)
        at org.scijava.Context.<init>(Context.java:244)
        at org.scijava.Context.<init>(Context.java:203)
        at org.scijava.Context.<init>(Context.java:142)
        at org.scijava.Context.<init>(Context.java:98)
        at org.scijava.Context.<init>(Context.java:86)
        at net.imagej.ImageJ.<init>(ImageJ.java:82)
        at net.imagej.Main.launch(Main.java:61)
        at net.imagej.Main.main(Main.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:258)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:184)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:76)
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 18 at 168
        at javassist.CtClassType.getClassFile2(CtClassType.java:204)
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:98)
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:84)
        at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:711)
        at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:688)
        at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
        at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
        at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
        at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:391)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
        at javassist.compiler.Javac.compileStmnt(Javac.java:569)
        at javassist.expr.MethodCall.replace(MethodCall.java:235)
        at net.imagej.patcher.CodeHacker$7.edit(CodeHacker.java:685)
        at javassist.expr.ExprEditor.loopBody(ExprEditor.java:192)
        at javassist.expr.ExprEditor.doit(ExprEditor.java:91)
        at javassist.CtBehavior.instrument(CtBehavior.java:679)
        at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1278)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:669)
        ... 35 more
Caused by: java.io.IOException: invalid constant type: 18 at 168
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1044)
        at javassist.bytecode.ConstPool.read(ConstPool.java:984)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:125)
        at javassist.bytecode.ClassFile.read(ClassFile.java:770)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:114)
        at javassist.CtClassType.getClassFile2(CtClassType.java:191)
        ... 55 more
java.lang.IllegalArgumentException: Cannot modify method: public void run()
        at net.imagej.patcher.CodeHacker.insertAtTopOfMethod(CodeHacker.java:167)
        at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:229)
        at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:308)
        at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:109)
        at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:101)
        at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:495)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:397)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
        at net.imagej.legacy.DefaultLegacyService.<clinit>(DefaultLegacyService.java:124)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:302)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:269)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:231)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:166)
        at org.scijava.Context.<init>(Context.java:244)
        at org.scijava.Context.<init>(Context.java:203)
        at org.scijava.Context.<init>(Context.java:142)
        at org.scijava.Context.<init>(Context.java:98)
        at org.scijava.Context.<init>(Context.java:86)
        at net.imagej.ImageJ.<init>(ImageJ.java:82)
        at net.imagej.Main.launch(Main.java:61)
        at net.imagej.Main.main(Main.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:258)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:184)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:76)
Caused by: java.lang.IllegalArgumentException: No such class: JavaScriptEvaluator
        at net.imagej.patcher.CodeHacker.getClass(CodeHacker.java:880)
        at net.imagej.patcher.CodeHacker.getMethod(CodeHacker.java:906)
        at net.imagej.patcher.CodeHacker.getBehavior(CodeHacker.java:896)
        at net.imagej.patcher.CodeHacker.insertAtTopOfMethod(CodeHacker.java:158)
        ... 33 more
Caused by: javassist.NotFoundException: JavaScriptEvaluator
        at javassist.ClassPool.get(ClassPool.java:450)
        at net.imagej.patcher.CodeHacker.getClass(CodeHacker.java:875)
        ... 36 more
java.lang.IllegalArgumentException: Cannot handle app name in ij.ImageJ's public <init>(java.applet.Applet applet, int mode)
        at net.imagej.patcher.CodeHacker.replaceAppNameInCall(CodeHacker.java:445)
        at net.imagej.patcher.LegacyExtensions.insertAppNameHooks(LegacyExtensions.java:404)
        at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:290)
        at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:308)
        at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:109)
        at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:101)
        at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:495)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:397)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
        at net.imagej.legacy.DefaultLegacyService.<clinit>(DefaultLegacyService.java:124)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:302)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:269)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:231)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:166)
        at org.scijava.Context.<init>(Context.java:244)
        at org.scijava.Context.<init>(Context.java:203)
        at org.scijava.Context.<init>(Context.java:142)
        at org.scijava.Context.<init>(Context.java:98)
        at org.scijava.Context.<init>(Context.java:86)
        at net.imagej.ImageJ.<init>(ImageJ.java:82)
        at net.imagej.Main.launch(Main.java:61)
        at net.imagej.Main.main(Main.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:258)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:184)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:76)
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 18 at 1
        at javassist.CtClassType.getClassFile2(CtClassType.java:204)
        at javassist.CtClassType.subtypeOf(CtClassType.java:304)
        at javassist.CtClassType.subtypeOf(CtClassType.java:319)
        at javassist.compiler.MemberResolver.compareSignature(MemberResolver.java:235)
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:107)
        at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:84)
        at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:711)
        at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:688)
        at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
        at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
        at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
        at javassist.compiler.Javac.compileStmnt(Javac.java:569)
        at javassist.expr.MethodCall.replace(MethodCall.java:235)
        at net.imagej.patcher.CodeHacker$4.edit(CodeHacker.java:426)
        at net.imagej.patcher.CodeHacker$4.edit(CodeHacker.java:440)
        at javassist.expr.ExprEditor.loopBody(ExprEditor.java:220)
        at javassist.expr.ExprEditor.doit(ExprEditor.java:91)
        at javassist.CtBehavior.instrument(CtBehavior.java:679)
        at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1278)
        at net.imagej.patcher.CodeHacker.replaceAppNameInCall(CodeHacker.java:401)
        ... 34 more
Caused by: java.io.IOException: invalid constant type: 18 at 1
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1044)
        at javassist.bytecode.ConstPool.read(ConstPool.java:984)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:125)
        at javassist.bytecode.ClassFile.read(ClassFile.java:770)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:114)
        at javassist.CtClassType.getClassFile2(CtClassType.java:191)
        ... 55 more`

I'm not sure how to repair the function. @arokem, any ideas how to fix?

**Comment by ccurtis7** [comment]
I think I figured it out. It has to do with the default fiji_bin behavior, or where the code looks for your installation of fiji. The key lines in `imagej.track` are:

`if fiji_bin is None:
        # if sys.platform == "darwin":
        #     fiji_bin = op.join(
        #         '/Applications/Fiji.app/Contents/MacOS/ImageJ-macosx')
        # elif sys.platform.startswith("linux"):
        #     fiji_bin = op.join(op.expanduser('~'), 'Fiji.app/ImageJ-linux64')
        fiji_bin = fijibin.BIN.split('.exe')[0]`

Currently, if you don't specify where Fiji is installed, it will download Fiji using the python module `fijibin`. This was working just fine up until 3 weeks ago, but something must have changed. This version of Fiji doesn't seem to work, and gives the errors above. If you download the most recent version of Fiji yourself, and then specify it with the `fiji_bin` variable, the code works just fine. 

I do need to think how we should modify the default behavior. Ideally, the user wouldn't need to manually specify where fiji is located. I superficially addressed this last time by just downloading it, but that solution no longer seems to work. Thinking on it.

**Comment by ccurtis7** [comment]
I think I will revert to the original default behavior in the commented section that assumes where Fiji is installed based on your system. Testing.

**Comment by stsievert** [comment]
> This was working just fine up until 3 weeks ago, but something must have changed.

Hm... the last commit on [fijibin] is back in May 2015, and it downloads a fixed version (20141125, [source][1]). What else could have changed?

[1]:https://github.com/arve0/fijibin/blob/a3d2e983cb9ff2bcbb56a800084bc3b35cb9292f/fijibin/__init__.py#L23
> I think I will revert to the original default behavior in the commented section that assumes where Fiji is installed based on your system. Testing.

It'd be nice if the user didn't have to download Fiji too.

[fijibin]:https://github.com/arve0/fijibin

**Comment by ccurtis7** [comment]
I can't pinpoint why the `fijibin` method no longer works. As you pointed out, requiring the user to install Fiji is a disadvantage to the current setup. I tried to ensure Fiji would be installed correctly by adding an installation step in the setup.py file. Let me know if you like this configuration. It's currently working properly on Travis.

**Comment by ccurtis7** [comment]
Yeah, this was fixed a while ago, as explained above.
